name: Deploy Hello World Web App - Production

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda function
        run: zip -j lambda.zip lambda/index.js


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend-config="key=hello-world-app/prod/terraform.tfstate"

      - name: Terraform plan
        run: terraform plan
      
      - name: Terraform Apply
        run: terraform apply -auto-approve

